# yaml-language-server: $schema=https://platen.io/schemas/hugo/config/schema.json

baseURL: 'https://timestamper.knoxy.ca'
languageCode: 'en-us'
title: 'TimeStamper'
module:
  # Replacements are used for theme authoring. Do not uncomment unless you know what you're doing.
  # replacements: >-
  #   github.com/corbob/hugo-theme -> /workspaces/hugo-theme
  imports:
    - path: 'github.com/corbob/hugo-theme'
params:
  favicon: img/favicon.png
